### ISSUE TITLE
weird errors saying file does not exist

### ISSUE THREAD

**Issue by Ccode-lang** [vlang/vinix#45]

**Comment by Ccode-lang** [comment]
![Snip20210901_1](https://user-images.githubusercontent.com/78437178/131764779-dd4139ce-2846-47cb-a30e-74b802543dc8.png)

**Comment by Ccode-lang** [comment]
this occurs for many commands

**Comment by streaksu** [comment]
Please could you show a more concrete example? The error you explain is not shown in the screenshot attached.

**Comment by Ccode-lang** [comment]
It will (sometimes) do this when executing any command.

**Comment by Ccode-lang** [comment]
It says that a string of random characters can not be found.

**Comment by JalonSolov** [comment]
How does that equate to a file not found?  It just says "extra operand".

**Comment by streaksu** [comment]
@Ccode-lang if you mean the graphical glitch when printing, my theory is that the cause is that specific set of quotations is not supported by the terminal, causing the `'sh'` to turn into `(glitch)sh(glitch)`. This bug will be looked into further.

Regarded the `file not found` errors, I am afraid that without a reproducible example, or any leads, we cannot really do much.

I will mark invalid and close as the main issue referenced here, which is the `file not found` errors, cannot be really worked on with this information.

**Comment by Ccode-lang** [comment]
it does it when running operations on files also.

**Comment by Ccode-lang** [comment]
Happened with mv once. (The whole thing might just be a fluke with m1)

**Comment by Ccode-lang** [comment]
I was never able to find any more info other than this sorry.
